"""Constants for the Homey P1 integration."""

DOMAIN = "homey_p1"
DEFAULT_NAME = "Homey P1"
DEFAULT_PORT = 80
WS_PATH = "/ws"
RECONNECT_DELAY_SECONDS = 5
MAX_RECONNECT_DELAY_SECONDS = 300
CONNECT_TIMEOUT_SECONDS = 10
TELEGRAM_TIMEOUT_SECONDS = 30
VALIDATION_TIMEOUT_SECONDS = 15
TRANSIENT_FAILURE_GRACE_SECONDS = 15
